### ISSUE TITLE
tring indices must be integers

### ISSUE THREAD

**Issue by heinbrian** [Bart-o-zz/ThreatRecon#1]
Transform Get Indicators from RootNode returned with an error: Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-1.1-py2.7.egg/canari/maltego/utils.py", line 228, in local_transform_runner
    config
  File "threatrecon/transforms/RootNodeToIndicator.py", line 48, in dotransform
    indtype = indicator['Type'].lower().strip()
TypeError: string indices must be integers

Transform Get Indicators from RootNode returned with an error: Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-1.1-py2.7.egg/canari/maltego/utils.py", line 228, in local_transform_runner
    config
  File "threatrecon/transforms/RootNodeToIndicator.py", line 48, in dotransform
    indtype = indicator['Type'].lower().strip()
TypeError: string indices must be integers

Transform Get Indicators from RootNode done

**Comment by Bart-o-zz** [comment]
Added if list == type(found):
