### ISSUE TITLE
Issue with SSL version request (TSL v1.1 vs 1.2?)

### ISSUE THREAD

**Issue by stormrainer** [Bart-o-zz/ThreatRecon#5]
When making a request all modules error out on SSL handling. Considering there is a workaroind in the other repo for using ThreatRecon, this should also be implemented in these connection requests:

https://github.com/dechko/threatrecon/blob/master/sslv3.py

Error from Maltego on Transform request:

Transform 'IPAddress to Threat Recon' returned the following error(s):
- Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\canari-1.0-py2.7.egg\canari\commands\run_transform.py", line 98, in run
    config
  File "threatrecon\transforms\IPAddressToThreatRecon.py", line 41, in dotransform
    cache, found = search(request.value, cache=False)
  File "threatrecon\transforms\common\client.py", line 67, in search
    return False, query_threat_recon(value)
  File "threatrecon\transforms\common\client.py", line 44, in query_threat_recon
    r = requests.post("https://api.threatrecon.co:8080/api/v1/search", data=params, headers=headers)
  File "C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\api.py", line 88, in post
    return request('post', url, data=data, *_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\sessions.py", line 456, in request
    resp = self.send(prep, *_send_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\sessions.py", line 559, in send
    r = adapter.send(request, *_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\adapters.py", line 382, in send
    raise SSLError(e, request=request)
  SSLError: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by stormrainer** [comment]
Would like to close after reading known issues and work around which includes using the following:
https://github.com/dechko/threatrecon/blob/master/sslv3.py
