### ISSUE TITLE
ImportError: No module named threatrecon.transforms.WhoisToThreatRecon

### ISSUE THREAD

**Issue by elhoim** [Bart-o-zz/ThreatRecon#7]
On MacOSX 10.9.4 with `Python 2.7.5 (v2.7.5:ab05e7dd2788, May 13 2013, 13:18:45)`

I get the following error message:

```
Transform Whois Domain name returned with an error: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-1.0-py2.7.egg/canari/commands/run_transform.py", line 73, in run
    transform_module = import_transform(transform)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/canari-1.0-py2.7.egg/canari/commands/common.py", line 192, in import_transform
    return __import__(script, globals(), locals(), ['dotransform'])
ImportError: No module named threatrecon.transforms.WhoisToThreatRecon
```

**Comment by heinbrian** [comment]
@elhoim maybe you should let everyone know that you are running a home-brewd python? Your error message makes me think that no Canari Framework transform will work out of the box

Go to the Transform manager and edit the command line parameters from /usr/local/dispatcher to the respective correct dispatcher for your OS  - it might be at /usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/bin/dispatcher
